apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deployment
  labels:
    app: resultserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resultserver 
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - name: resultserver
        image: paulkellerman/phonebookapp-resultserver:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: phonebook-configmap
        - secretRef:
            name: phonebook-secret